server:
  port: ${svc_discovery-consumer_port}

spring:
  application:
    name: ${svc_discovery-consumer}
  cloud:
    nacos:
      username: ${nacos_username}
      password: ${nacos_password}
      discovery:
        server-addr: ${nacos_host}:${nacos_port}
        namespace: ${nacos_namespace}
        group: ${nacos_groupId}
    sentinel:
      transport:
        dashboard: localhost:8080
      eager: true
      datasource:
        ds1:
          file:
            file: 'classpath: flowrule.json'
            data-type: json
            rule-type: flow
        ds2:
          file:
            file: 'classpath: degraderule.json'
            data-type: json
            rule-type: degrade

feign:
  sentinel:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'